### ISSUE TITLE
Path prefix warning

### ISSUE THREAD

**Issue by BWibo** [tum-gis/sddi-ckan-k8s#13]
### What happened?

On deployment (`heml upgrade` or `heml install`), this warning is shown sometimes:
```text
W0807 09:43:50.396997    2602 warnings.go:70] path /(.*) cannot be used with pathType Prefix
```
It needs to be investigated what this is about and why it's not shown everytime, just every now and then.

### Steps to reproduce

1. Deploy or upgrade helm chart and see warning

### Configuration

```YAML
ckan-instance-this-happened:
  - catalog.savenow.de
```

### Helm chart version

sddi-ckan-1.1.5 and older versions too

### SDDI CKAN Docker image version

ghcr.io/tum-gis/ckan-sddi:1.1.3

#### Helm
   ```
   version.BuildInfo{Version:"v3.12.2", GitCommit:"1e210a2c8cc5117d1055bfaa5d40f51bbc2e345e", GitTreeState:"clean", GoVersion:"go1.20.5"}
   ```
#### Kubernetes

```yml
kubectl version  --output=yaml
clientVersion:
  buildDate: "2023-05-17T14:20:07Z"
  compiler: gc
  gitCommit: 7f6f68fdabc4df88cfea2dcf9a19b2b830f1e647
  gitTreeState: clean
  gitVersion: v1.27.2
  goVersion: go1.20.4
  major: "1"
  minor: "27"
  platform: linux/amd64
kustomizeVersion: v5.0.1
serverVersion:
  buildDate: "2023-06-19T16:12:25Z"
  compiler: gc
  gitCommit: 8cfcba0b15c343a8dc48567a74c29ec4844e0b9e
  gitTreeState: clean
  gitVersion: v1.25.11
  goVersion: go1.19.10
  major: "1"
  minor: "25"
  platform: linux/amd64
  ```
