### ISSUE TITLE
Allow parameterization of Ingress TSL secret name

### ISSUE THREAD

**Issue by BWibo** [tum-gis/sddi-ckan-k8s#19]
### Feature description

see title

**Comment by BWibo** [comment]
@lreneral: Would that be sufficient for you?

```yaml
# CKAN ingress
# ...
#... 
tls:
- hosts:
{{- range $domains }}
  - {{ . }}
{{- end }}
    secretName: {{ (coalesce .Values.ingress.tls.secretName .Values.global.ingress.tls.secretName (printf "%s-%s" (first $domains) "tls" )) | quote }}
# ...
# ...
```

This would allow to:
- Set a tls secet name for all Ingress using `.Values.global.ingress.tls.secretName`
- Overwrite the tsl secret name for each Ingress with: `.Values.ingress.tls.secretName`
- If none of those is set, it will default to the first entry in the `ingress.domains` list appended by `-tls`. For instance:

```yaml
global:
  ingress:
    domains:
      - abcd.de
      - cdef.de
``` 
==> TLS secet name=`abcd.de-tls`
